# Generated by Django 3.2 on 2021-04-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smbdOrderID', models.CharField(max_length=10)),
                ('smbdOrderDate', models.DateField()),
                ('smbdOrderTotalBeforeCoupons', models.IntegerField()),
                ('smbdOrderShipping', models.IntegerField()),
                ('smbdOrderFees', models.DecimalField(decimal_places=2, max_digits=20)),
                ('smbdOrderDiscounts', models.DecimalField(decimal_places=2, max_digits=20)),
                ('smbdOrderCouponNames', models.CharField(max_length=100)),
                ('smbdOrderAfterCoupons', models.IntegerField()),
                ('smbdOrderProductCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('smbdOrderShippingVendor', models.CharField(max_length=30)),
                ('smbdOrderPaymentMethod', models.CharField(max_length=30)),
                ('smbdOrderShippingVendorPayable', models.DecimalField(decimal_places=2, max_digits=20)),
                ('smbdOrderDateCompleted', models.DateField()),
            ],
        ),
    ]
